/* tslint:disable */
/* eslint-disable */
/**
 * Care Mastere API
 * Care Mastere API specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: chinthyelim@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
